sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "stable"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: "prepare"
      script:
        - npm i
    - stage: "test"
      script:
        - npm run lint
        - npm run test
        - npm run e2e
    - stage: "build"
      script:
        - npm run build
    - stage: "deploy"
      script:
        - npm run deploy