language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: "prepare"
      script:
        - npm install
    - stage: "test"
      script:
        - npm run lint
        - npm run test
    - stage: "build"
      script:
        - npm run build
    - stage: "deploy"
      script:
        - npm i -g firebase-tools
        - firebase deploy --token "$FIREBASE_TOKEN"